### ISSUE TITLE
The code is missing. I cannot use the code for evaluation. 

### ISSUE THREAD

**Issue by ravi-aii** [Zxl19990529/Class-driven-Scribble-Promotion-Network#1]
The file 'res50_ASPP_lorm' is missing.

ImportError: cannot import name 'res50_ASPP_lorm' from 'models' (unknown location)
Please provide the complete code.

**Comment by Zxl19990529** [comment]
Hi, I have just uploaded the res50_ASPP_lorm.py to the "models/" folder and updated the utils.py. Try again.
(The CAMATT in that code is another name for Lorm, the code is the same.)
