### ISSUE TITLE
How to generate pseudo labels?

### ISSUE THREAD

**Issue by Fluestech** [Zxl19990529/Class-driven-Scribble-Promotion-Network#2]
Hi,

Great job on the project!

Could you let me know where I can find the BMP code?

Thanks!

**Comment by Zxl19990529** [comment]
Hi, I‘m sorry that I forgot to release the pseudo labels used in the paper, here is the link [google drive](https://drive.google.com/drive/folders/1HrdPsI0K0udiPBy2_2y-j51oy205hBHH?usp=sharing) . I also updated the Readme of this project.
However, I do not have the authority to publicly disclose the code of BMP. It's recommanded to ask for the code from the first author of "Branches Mutual Promotion for End-to-End Weakly Supervised Semantic Segmentation".

**Comment by Fluestech** [comment]
Hi @Zxl19990529 ,

Many thanks for this!

Btw, shouldn’t the results of weakly SSS generally be lower than those of fully SSS? I'm curious about how much lower they will be.

Thanks

**Comment by Zxl19990529** [comment]
Yes, the results of weakly SSS are lower than fully supervised ones. In general, the rank is :
Image supervised< scribble supervised< Fully supervised
I have uploaded the quantization results of the fully supervised ones in Readme page for reference.

**Comment by Fluestech** [comment]
OK, thanks!
